// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeWOXaX8ttFPfBd_rF6dUygujoguQW8jI',
    appId: '1:440314809623:android:ab0199663ca15d2d00fb52',
    messagingSenderId: '440314809623',
    projectId: 'teni-87b1a',
    storageBucket: 'teni-87b1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY-mrbUrEB5iW7iRswlZAjuPiQUB20BvU',
    appId: '1:440314809623:ios:222552e6ab620ddd00fb52',
    messagingSenderId: '440314809623',
    projectId: 'teni-87b1a',
    storageBucket: 'teni-87b1a.appspot.com',
    androidClientId: '440314809623-9901nnr5rdd0se8ok37kvg4paeubeg1k.apps.googleusercontent.com',
    iosClientId: '440314809623-nd46u14bt4amcn1eotulc0tb3cuqopmq.apps.googleusercontent.com',
    iosBundleId: 'com.example.walletApp',
  );
}
